#!/usr/bin/env python
# -*- coding: utf-8 -*-

# filename   : call-set.py
# created at : 2012年07月17日 星期二 08时21分43秒
# author     : Jianing Yang <jianingy.yang AT gmail DOT com>

__author__ = 'Jianing Yang <jianingy.yang AT gmail DOT com>'

from mechanize import Browser
import urllib
import urllib2
import os
import sys
import cookielib

base_url = 'https://ipt.uc.alibaba-inc.com:8443'


def debug(s):
    print >>sys.stderr, s


def try_login():
    auth = os.path.expanduser('~/.cisco-voip-auth')
    if os.path.exists(auth):
        line = file(auth).readline()
        username, password = line.split(' ', 2)
        return login(username, password)
    else:
        from getpass import getpass
        username = raw_input('username: ')
        password = getpass(prompt='password: ')
        file(auth, 'w+').write('%s %s' % (username, password))
        return login(username, password)


def login(username, password):
    br = Browser()
    login_url = '%s/%s' % (base_url, 'ccmuser/WEB-INF/pages/j_security_check')
    data = {'j_username': username, 'j_password': password}

    # Cookie Jar
    cj = cookielib.LWPCookieJar()
    br.set_cookiejar(cj)

    # Browser options
    br.set_handle_equiv(True)
    br.set_handle_gzip(False)
    br.set_handle_redirect(True)
    br.set_handle_referer(True)
    br.set_handle_robots(False)
    #br.set_debug_redirects(True)
    #br.set_debug_http(True)
    br.addheaders = [('User-agent', 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.1) Gecko/2008071615 Fedora/3.0.1-1.fc9 Firefox/3.0.1')]
    debug('login to Cisco Unified CM with user %s' % username)
    response = br.open(login_url, urllib.urlencode(data))

    debug('redirect to device setting page')
    device_url = '%s/%s' % (base_url, 'ccmuser/deviceRedirect.do')
    response = br.open(device_url)
    return br


def start_line_setting(br):
    settings = dict()

    device_url = '%s/%s' % (base_url, 'ccmuser/lineSettingsRedirect.do')
    response = br.open(device_url)
    return br


def set_call_forwarding(number):
    br = try_login()
    br = start_line_setting(br)

    br.select_form('linesettingsForm')
    br.find_control('cfucheck').items[0].selected = True
    br['cfadestination'] = number
    br.form.action = '%s/%s' % (base_url, 'ccmuser/lineSettingsSave.do')
    br.submit()


def disable_call_forwarding():
    br = try_login()
    br = start_line_setting(br)

    br.select_form('linesettingsForm')
    br.find_control('cfucheck').items[0].selected = True
    br['cfadestination'] = ''
    br.form.action = '%s/%s' % (base_url, 'ccmuser/lineSettingsSave.do')
    br.submit()


def usage():
    print """usage: call-set [options]
cisco unified cm user option cli tool
mandatory options:

    -h                      help message
    -f|--forward NUMBER     forward call to NUMBER. use -f DISABLE to disable
                            call forwarding.

please send bugs/patches to jianingy.yang AT gmail DOT com
"""


def run():

    import getopt

    try:
        opts, args = getopt.getopt(sys.argv[1:], 'hf:', ['help', 'forward='])
    except getopt.GetoptError as e:
        print (e)
        usage()
        sys.exit(2)

    for o, a in opts:
        if o == '-h':
            usage()
            sys.exit(0)
        elif o in ('-f', '--forward'):
            number = a
            if number.lower() == 'disable':
                disable_call_forwarding()
                sys.exit(0)
            else:
                set_call_forwarding(number)
                sys.exit(0)


if __name__ == '__main__':
    run()
    usage()
